volumes:
  ckan_storage:
  pg_data:
  solr_data:
  pip_cache:
  site_packages:
  local_bin:
  home_dir:

services:
  ckan-dev:
    build:
      context: ckan/
      dockerfile: Dockerfile.dev
      args:
        - TZ=UTC
    env_file:
      - .env.dev.config
      - .env.dev.secrets
    links:
      - db
      - solr
      - redis
    ports:
      - '0.0.0.0:5000:5000'
    volumes:
      - ckan_storage:/var/lib/ckan
      - ./src:/srv/app/src_extensions
      - pip_cache:/root/.cache/pip
      - site_packages:/usr/local/lib/python3.10/site-packages
      - local_bin:/usr/local/bin
      - home_dir:/srv/app/
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '-qO', '/dev/null', 'http://localhost:5000']
      interval: 60s
      timeout: 10s
      retries: 3

  datapusher:
    image: ckan/ckan-base-datapusher:0.0.20
    env_file:
      - .env.dev.config
      - .env.dev.secrets
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '-qO', '/dev/null', 'http://localhost:8800']
      interval: 60s
      timeout: 10s
      retries: 3

  db:
    build:
      context: postgresql/
    env_file:
      - .env.dev.config
      - .env.dev.secrets
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-U', '${POSTGRES_USER}', '-d', '${POSTGRES_DB}']

  solr:
    image: ckan/ckan-solr:2.9-solr9-spatial
    volumes:
      - solr_data:/var/solr
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '-qO', '/dev/null', 'http://localhost:8983/solr/']

  redis:
    image: redis:6
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', '-e', 'QUIT']
